#pragma config(Sensor, S1,     lightsensor,    sensorLightActive)
#pragma config(Sensor, S2,     sonicsensor,    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

nSyncedMotors=synchBC;
nSyncedTurnRatio=100;


float x=SensorValue(lightsensor);
motor[motorB]=-100;
wait1Msec(500);
motor[motorB]=0;
wait1Msec(500);

float y=SensorValue(lightsensor);
float threshhold=(y+x)/2;
ClearTimer(T1);
while( time1[T1]< 500000)
{
	motor[motorA]=4;

	while(SensorValue(lightsensor)>threshhold)
		{
			if(SensorValue(sonicsensor)<100)
		{	nSyncedTurnRatio=100;



			motor[motorB]=100;

			}

			else
			{
				nSyncedTurnRatio=-50;
				motor[motorB]=10;
				}

			}

nSyncedTurnRatio=100;
motor[motorB]=-50;
wait1Msec(2000);
nSyncedTurnRatio=-50;
motor[motorB]=20;
wait1Msec(1500);
nSyncedTurnRatio=100;
motor[motorB]=50;
wait1Msec(500);
nSyncedTurnRatio=-50;
motor[motorB]=20;
wait1Msec(500);
nSyncedTurnRatio=100;
motor[motorB]=50;
wait1Msec(1000);
nSyncedTurnRatio=-50;
motor[motorB]=20;

}
}
